Schrattenholz\Order\Preis:
  extensions:
    - Schrattenholz\OrderSale\OrderSale_PreisExtension
    - Schrattenholz\OrderSale\OrderSale_OrderExtension
Schrattenholz\Order\Product:
  extensions:
    - Schrattenholz\OrderSale\OrderSale_ProductExtension
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Schrattenholz\OrderSale\OrderSale_OrderExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Schrattenholz\OrderSale\OrderSale_OrderExtension
Schrattenholz\OrderProfileFeature\OrderProfileFeature_ProductContainer:
  extensions:
    - Schrattenholz\OrderSale\OrderSale_ProductContainer